Repository JennyKmu/RRO_savefile_editor, pull requests merged in 2021-11, with the labels that each got.

#13 Feature cars contents
  README.md
  RRO_savefile_editor/UI/rollingStockData.py
  RRO_savefile_editor/UI/ui.py
  RRO_savefile_editor/main.py
Labels: Feature

#19 Restock Menu
  RRO_savefile_editor/UI/rollingStock.py
  RRO_savefile_editor/UI/ui.py
Labels: Feature

#23 Utility filling added
  RRO_savefile_editor/UI/industryPlacables.py
  RRO_savefile_editor/UI/ui.py
Labels: Feature

#29 Feature: Smart Tree Respawn
  RRO_savefile_editor/GVAS/GVAS.py
  RRO_savefile_editor/UI/betterDefaultRemovedTrees.py
  RRO_savefile_editor/UI/industryPlacables.py
  RRO_savefile_editor/UI/ui.py
  RRO_savefile_editor/main.py
Labels: enhancement

#33 Feature: Industry Content Editor
  RRO_savefile_editor/UI/industryPlacables.py
  RRO_savefile_editor/UI/ui.py
Labels: Feature

#35 Feature: Edit Attachments
  RRO_savefile_editor/UI/rollingStock.py
  RRO_savefile_editor/UI/ui.py
Labels: Feature

#42 Feature: Player Teleport
  RRO_savefile_editor/UI/defaultRemovedTrees.py
  RRO_savefile_editor/UI/industryPlacables.py
  RRO_savefile_editor/UI/playerTeleportReferences.py
  RRO_savefile_editor/UI/rollingStock.py
  RRO_savefile_editor/UI/ui.py
  RRO_savefile_editor/UI/uidev.py
  RRO_savefile_editor/UI/uiutils.py
  RRO_savefile_editor/main.py
Labels: enhancement, Feature
